from datetime import datetime
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), index=True, unique=True, nullable=False)
    username = db.Column(db.String(64), index=True, unique=True, nullable=False)
    password_hash = db.Column(db.String(256))
    role = db.Column(db.String(20), default='Student') # Roles: Admin, Mentor, Student

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

class Topic(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)
    description = db.Column(db.String(255))

class QuizResult(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    topic_id = db.Column(db.Integer, db.ForeignKey('topic.id'), nullable=False)
    score = db.Column(db.Float, nullable=False) # e.g. percentage 0.0 to 1.0
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship('User', backref=db.backref('quiz_results', lazy=True))
    topic = db.relationship('Topic', backref=db.backref('quiz_results', lazy=True))

class KnowledgeGap(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    topic_id = db.Column(db.Integer, db.ForeignKey('topic.id'), nullable=False)
    gap_score = db.Column(db.Float, nullable=False) # AI generated score of how badly they need to revise
    suggested_revision = db.Column(db.String(255))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship('User', backref=db.backref('knowledge_gaps', lazy=True))
    topic = db.relationship('Topic', backref=db.backref('gaps', lazy=True))

class Note(db.Model):
    """Stores user uploaded notes in the Library section"""
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    title = db.Column(db.String(150), nullable=False)
    content = db.Column(db.Text, nullable=False) # Or file path / extracted text
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship('User', backref=db.backref('notes', lazy=True))

class Question(db.Model):
    """Stores MCQ questions generated by the AI from Notes or assigned to Topics"""
    id = db.Column(db.Integer, primary_key=True)
    note_id = db.Column(db.Integer, db.ForeignKey('note.id'), nullable=True)
    topic_id = db.Column(db.Integer, db.ForeignKey('topic.id'), nullable=True)
    question_text = db.Column(db.Text, nullable=False)
    option_a = db.Column(db.String(255), nullable=False)
    option_b = db.Column(db.String(255), nullable=False)
    option_c = db.Column(db.String(255), nullable=False)
    option_d = db.Column(db.String(255), nullable=False)
    correct_option = db.Column(db.String(1), nullable=False) # 'A', 'B', 'C', or 'D'
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    note = db.relationship('Note', backref=db.backref('questions', lazy=True))
    topic = db.relationship('Topic', backref=db.backref('questions', lazy=True))


class QuizSession(db.Model):
    """Represents one MCQ test attempt generated from notes/topics."""
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    note_id = db.Column(db.Integer, db.ForeignKey('note.id'), nullable=True)
    topic_id = db.Column(db.Integer, db.ForeignKey('topic.id'), nullable=True)
    score = db.Column(db.Float, nullable=False, default=0.0)  # 0.0 - 1.0
    correct_count = db.Column(db.Integer, nullable=False, default=0)
    total_questions = db.Column(db.Integer, nullable=False, default=0)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship('User', backref=db.backref('quiz_sessions', lazy=True))
    note = db.relationship('Note', backref=db.backref('quiz_sessions', lazy=True))
    topic = db.relationship('Topic', backref=db.backref('quiz_sessions', lazy=True))


class QuizAnswer(db.Model):
    """Stores each answer selected by a user for a question in a quiz session."""
    id = db.Column(db.Integer, primary_key=True)
    quiz_session_id = db.Column(db.Integer, db.ForeignKey('quiz_session.id'), nullable=False)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'), nullable=False)
    selected_option = db.Column(db.String(1), nullable=False)
    is_correct = db.Column(db.Boolean, nullable=False, default=False)

    quiz_session = db.relationship('QuizSession', backref=db.backref('answers', lazy=True, cascade='all, delete-orphan'))
    question = db.relationship('Question', backref=db.backref('quiz_answers', lazy=True))


class QuizQuestionState(db.Model):
    """Tracks two-attempt lifecycle of each question inside a quiz session."""
    id = db.Column(db.Integer, primary_key=True)
    quiz_session_id = db.Column(db.Integer, db.ForeignKey('quiz_session.id'), nullable=False)
    question_id = db.Column(db.Integer, db.ForeignKey('question.id'), nullable=False)
    order_index = db.Column(db.Integer, nullable=False)
    first_attempt_option = db.Column(db.String(1), nullable=True)
    second_attempt_option = db.Column(db.String(1), nullable=True)
    is_correct = db.Column(db.Boolean, nullable=False, default=False)
    is_completed = db.Column(db.Boolean, nullable=False, default=False)
    feedback = db.Column(db.String(500), nullable=True)
    hint = db.Column(db.String(500), nullable=True)

    quiz_session = db.relationship('QuizSession', backref=db.backref('question_states', lazy=True, cascade='all, delete-orphan'))
    question = db.relationship('Question', backref=db.backref('quiz_states', lazy=True))

class ChatMessage(db.Model):
    """Stores AI Chatbot conversation history"""
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    message = db.Column(db.Text, nullable=False)
    is_bot = db.Column(db.Boolean, default=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship('User', backref=db.backref('chat_messages', lazy=True))

class UserActivity(db.Model):
    """Tracks user activity like taking a quiz or uploading a note for the Days Active calendar"""
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    activity_type = db.Column(db.String(50)) # e.g. 'Quiz Taken', 'Note Uploaded'
    details = db.Column(db.String(255))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship('User', backref=db.backref('activities', lazy=True))
